# fly.toml app configuration file generated for skotti-todo on 2023-05-29T15:24:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skotti-todo"
primary_region = "ams"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
